# https://docs.codecov.io/docs/codecov-yaml
# https://docs.codecov.io/docs/notifications
codecov:
  notify:
    require_ci_to_pass: false

# https://docs.codecov.io/docs/pull-request-comments
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  branches: null
ignore:
  - bin
  - demo/images
  - templates
  - test

# https://docs.codecov.io/docs/coverage-configuration
coverage:
  range: 50..100
