# CONFIG
# ======
cache:
  yarn: true
  directories:
    - node_modules
language: node_js
stages:
  - test
  - release

# JOB EXPANSION
# ======
env:
  - YARN_GPG=no # needed for windows to exit correctly
node_js:
  - 11
  - 10
os:
  - osx
  - linux
  - windows

# JOB LIFECYCLE
# ======
# before_install: # anything needed to install dependencies
# install:        # install dependencies
# before_script:  # anything needed to run the main script
# script:         # the main script
# before_cache:   # clean up cache
# after_success:  # callbqck
# after_failure:  # callbqck
# before_deploy:  # anything needed to run the main deployment script
# deploy:         # the main deployment script
# after_deploy:   #
# after_script:   #
script:
  - yarn ci-test

jobs:
  include:
    - stage: release
      script:
        - yarn ci-test
        - yarn ci-coverage
