language: node_js
env:
  - YARN_GPG=no
node_js:
  - node
  # - 11
  # - 10
os:
  - osx
  # - linux
  # - windows
script:
  - yarn test
jobs:
  include:
    - stage: coveralls
      install: npm i -g c8 coveralls
      script: c8 report --reporter=text-lcov | coveralls
