# see README.md for details
# name:
# data:
#   foo:
#     key: value
# demo:
#   host:
#   port:
#   tests:
#   engines:
#     css:
#     html:
#     js:
#   data:
#     foo:
#       key: new value
# test:
#   data:
#     foo:
#       key: new value
