// Generated by CoffeeScript 1.7.1

/*
 * * bumper core
 * * https://github.com/brewster1134/bumper
 * *
 * * @version 0.0.1
 * * @author Ryan Brewster
 * * Copyright (c) 2014
 * * Licensed under the MIT license.
 */

(function() {
  (function(root, factory) {
    var _base, _base1;
    if (typeof define === 'function' && define.amd) {
      return define([], function() {
        return factory();
      });
    } else {
      window.Bumper || (window.Bumper = {});
      (_base = window.Bumper).Responsive || (_base.Responsive = {});
      (_base1 = window.Bumper.Responsive).Image || (_base1.Image = {});
      return factory();
    }
  })(this, function() {});

}).call(this);
