// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    $(window).resize(function() {
      var breakpoint;
      breakpoint = $(window).innerWidth() <= 800 ? 'mobile' : 'desktop';
      return Bumper.Responsive.Image.Background.resizeAll(breakpoint);
    });
    $(window).trigger('resize');
    return $(window).on('bumper.responsive.image.background.loaded', function(e, data) {
      return console.log('Image Loaded');
    });
  });

}).call(this);
