// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    $(window).resize(function() {
      var breakpoint;
      breakpoint = $(window).innerWidth() <= 800 ? 'mobile' : 'desktop';
      Bumper.Responsive.BackgroundImage.resizeAll(breakpoint);
      return Bumper.Responsive.Image.resizeAll(breakpoint);
    });
    return $(window).trigger('resize');
  });

}).call(this);
